### ISSUE TITLE
SDK: GraphComponent does not preserve already build graph when getting Attribute

### ISSUE THREAD

**Issue by mrzzy** [joeltio/bento-box#39]
### Problem
Given this example  building a computation graph with `GraphComponent`:
```python
car[Position].x = 3
car[Position].y = car[Position].x + 2
```
The following computational graph is expected to be generated: 
- The graph built to output `car[Position].x` should also be preserved and used when building the graph use to output `car[Position].y`:
```yaml
outputs:
- mutateAttr:
    attribute: x
    component: position
    entityId: 1
  toNode:
    # this subgraph should be preserved for being used later as sub graph of outputting  'car[Position].y'
      heldValue:
        dataType:
          primitive: INT32
        primitive:
          int32: 3
- mutateAttr:
    attribute: y
    component: position
    entityId: 1
  toNode:
    addOp:
      x:
        # this sub graph should be derived from the graph used to output 'car[Position].x'
        constOp:
          heldValue:
            dataType:
              primitive: INT32
            primitive:
              int32: 3
      y:
        constOp:
          heldValue:
            dataType:
              primitive: INT32
            primitive:
              int32: 2
```

- Currently, this computation graph is generated by `GraphComponent`, which does not preserve the `car[Position].x = 3` subgraph when generating the graph to output `car[Position].y`:
```yaml
inputs:
- retrieveAttr:
    attribute: x
    component: position
    entityId: 1
outputs:
- mutateAttr:
    attribute: x
    component: position
    entityId: 1
  toNode:
    constOp:
      heldValue:
        dataType:
          primitive: INT32
        primitive:
          int32: 3
- mutateAttr:
    attribute: y
    component: position
    entityId: 1
  toNode:
    addOp:
      x:
        retrieveOp:
          # car[Position].x = 3 earlier is not being preserved here.
          retrieveAttr:
            attribute: x
            component: position
            entityId: 1
      y:
        constOp:
          heldValue:
            dataType:
              primitive: INT32
            primitive:
              int32: 2
```

### Fix
- [x] Update `GraphComponent`'s `get_attr()` to preserve and return  already built graph for the attribute if the attribute has been previously set.
- [x] Update `transform_ifelse` to `deepcopy()` input symbols. Since all branches of the if statement is traced and Python passes the `GraphComponent` by reference, graphs collected by each branch might interfere with each other. As such a `deepcopy()` is use to each sure each branch has a isolated copy of the `GraphComponent`.
