### ISSUE TITLE
Engine: Implement Implicit Type Casting

### ISSUE THREAD

**Issue by mrzzy** [joeltio/bento-box#48]
# Problem 
Currently the Engine enforces strict data typing when assigning to the attribute. 

For example compiling using the following component types:
```python
Velocity = ComponentDef(
    name="velocity",
    schema={
        "x": types.float64,
    },
)


Keyboard = ComponentDef(
    name="keyboard",
    schema={
        "key": types.byte,
    },
)
```
Compiling the following system:
```python
@sim.system
def issue_sys(g: Plotter):
    controls = g.entity(components=[Keyboard])
    controls[Keyboard].key = ord("a")
                                                                    
    car = g.entity(components=[Movement, Velocity, Position, Meta])
    car[Velocity].x = 2
```
generates the following Graph:
```yaml
outputs:
- mutateAttr:
    attribute: key
    component: keyboard
    entityId: 1
  toNode:
    constOp:
      heldValue:
        dataType:
          primitive: INT32
        primitive:
          int32: 97
- mutateAttr:
    attribute: x
    component: velocity
    entityId: 2
  toNode:
    constOp:
      heldValue:
        dataType:
          primitive: INT32
        primitive:
          int32: 2
```
causing the Engine to produce these Error message:
```
Something went wrong while running the initGraph of the simulation: Data type of given value does not match schema type for attribute key.
Something went wrong while running the initGraph of the simulation: Data type of given value does not match schema type for attribute x.
```

### Investigation
- The SDK's Graph Compiler infers the types of `2` and `97` (`ord("a") == 97`) as `INT32` and generates `mutateAttr` assigning them to `x` and `key`  of `float64` and `byte` types respectively.
- The Engine employing strict type checking finds that the data types don't exactly match for these assignments `INT32 != float64`, `INT32 != byte` and produces the error.

### Proposed Fix
- [ ] Implement implicit type casting on the Engine to be used when the types do not exactly match. Type casting should follow C++ semantics
