### ISSUE TITLE
Primitive Datatype Mismatch on when using Negate Operation

### ISSUE THREAD

**Issue by mrzzy** [joeltio/bento-box#53]
### Problem
Using the following Component Type:
```python
Velocity = ComponentDef(
    name="velocity",
    schema={
        "x": types.float64,
        "y": types.float64,
    },
)
```
To compile the following system:
```python
@sim.system
def negate_fn(g: Plotter):
    car = g.entity(components=[Movement, Velocity, Position, Meta])
    car[Velocity].y = -car[Velocity].x
```
compiles to the following Graph:
```yaml
inputs:
- retrieveAttr:
    attribute: x
    component: velocity
    entityId: 2
outputs:
- mutateAttr:
    attribute: y
    component: velocity
    entityId: 2
  toNode:
    subOp:
      x:
        constOp:
          heldValue:
            dataType:
              primitive: INT32
            primitive:
              int32: 0
      y:
        retrieveOp:
          retrieveAttr:
            attribute: x
            component: velocity
            entityId: 2
```

Upon running this compiled system on the Engine the following error  is thrown:
```
 Something went wrong while running system with ID: 2.: Primitive values must be the same type. Stored values Primitive[32-bit Integer] and Primitive[64-bit Float] do not match.
```

### Investigation
- Engine currently enforces strict data type checking #48.
- The Negate operation is current implemented in the SDK as:
```python
    def __neg__(self):
        # -x is equivalent to 0 - x
        return type(self).wrap(Node(sub_op=Node.Sub(x=wrap_const(0), y=self.node)))
```
- `wrap_const(0)` always generates a `INT32` `0`. When the engine executes `SubOp`  on the graph and finds that its data types are not identical (`INT32` != `FLOAT64`). It throws the error.

### Fix
PR #51
