### ISSUE TITLE
Engine: Implicit Type Conversion not done when assigning attribute with MutateOp

### ISSUE THREAD

**Issue by mrzzy** [joeltio/bento-box#54]
### Problem
Implicit Type Conversion implemented in #51 is not applied on `MutateOp`:
- Using this Component
```python
Meta = ComponentDef(
    name="meta",
    schema={
        "id": types.int64,
    },
)
```
- Assigning in Init Graph:
```python
car[Meta].id = 512
```
- Complies to:
```yaml
- mutateAttr:                                                                                                                               
    attribute: id                                                                                                                           
    component: meta                                                                                                                                                                                                                                                               
    entityId: 2                                                                                                                                                                                                                                                            
  toNode:                                                                                                                                                                                                                                                                  
    constOp:                                                                                                                                                                                                                                                             
      heldValue:                                                                                                                                                                                                                                                        
        dataType:                                                                                                                                                                                                                                                             
          primitive: INT32                                                                                                                                                                                                                                                        
        primitive:                                                                                                                                                                                                                                                        
          int32: 512 
```

This `mutateAttr`/MutateOp is flagged by the engine:
```
Something went wrong while running the initGraph of the simulation: Data type of given value does not match schema type for attribute id. Expected: Primitive.DataType[INT64], Got: Primitive.DataType[INT32].  
```
Even though Implicit Type Conversion should allow this and  convert (INT32 -> INT64) automatically.


### Proposed Fix
Implement Implicit Type Conversion for `MutateOp` assignments.
